apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: petclinic-app-rollout-bluegreen
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: petclinic-app-rollout-bluegreen
  template:
    metadata:
      labels:
        app: petclinic-app-rollout-bluegreen
    spec:
      containers:
        - name: petclinic-app
          image: lkh66913/petclinic-app:20240122053830685
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDeplaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: petclinic-app-log-storage
              mountPath: /logs
      volumes:
        - name: petclinic-app-log-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
      terminationGracePeriodSeconds: 30
  strategy:
    blueGreen:
      activeService: petclinic-app-rollout-bluegreen-active
      previewService: petclinic-app-rollout-bluegreen-preview
      autoPromotionEnabled: true
