apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: petclinic-app-hpa
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: petclinic-app-rollout-bluegreen
  targetCPUUtilizationPercentage: 70
