apiVersion: v1
kind: PersistentVolume
metadata:
  name: petclinic-app-gcp-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  gcePersistentDisk:
    pdName: my-persistent-disk
