apiVersion: v1
kind: PersistentVolume
metadata:
  name: petclinic-app-pv
  labels:
    type: petclinic-app-pv-local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/logs"
    type: DirectoryOrCreate
