name: petclinic-app
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!manifests/**'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date '+%Y%m%d%H%M%S%3N')"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        working-directory: ${{env.working-directory}}

      - name: Build with Gradle
        run: |
          ./gradlew build -x test
        shell: bash
        working-directory: ${{env.working-directory}}

      - name: Docker Image Build
        run: docker build -t lkh66913/petclinic-app:${{ steps.timestamp.outputs.timestamp }} .
        working-directory: ${{env.working-directory}}

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub Push
        run: docker push lkh66913/petclinic-app:${{ steps.timestamp.outputs.timestamp }}

      - name: Update app version for blue/green upgrade
        run: sed -i 's/petclinic-app:.*\$/petclinic-app:'${{ steps.timestamp.outputs.timestamp }}'/' manifests/petclinic-app/petclinic-app-rollouts.yaml

      - name: Commit version change
        run: |
          git config --global user.name 'hoonii2'
          git config --global user.email 'lkh66913@naver.com'
          git commit -am "deploy: new ${{ steps.timestamp.outputs.timestamp }} image versioning"
          git push
